### ISSUE TITLE
On the Newest Version of Floorp, following these directions appears to make two sidebars.

### ISSUE THREAD

**Issue by trlinden** [Alexcoder5/arc-inspired-floorp-setup#1]
This worked perfectly on the previous version of Floorp 11.15 (?) however, on the most recent version, 11.16.0, it seems to make two different sidebars on Mac OS X. The fire sidebar is the sideberry one, and looks great. The second looks like a default floorp sidebar that does not have the right aesthetic/color scheme.

Is there a way to remove this second sidebar? Otherwise, I love the project. It looks great!

**Comment by Alexcoder5** [comment]
I need a screenshot to fully understand what needs to be removed 

> This worked perfectly on the previous version of Floorp 11.15 (?) however, on the most recent version, 11.16.0, it seems to make two different sidebars on Mac OS X. The fire sidebar is the sideberry one, and looks great. The second looks like a default floorp sidebar that does not have the right aesthetic/color scheme.
> 
> Is there a way to remove this second sidebar? Otherwise, I love the project. It looks great!

**Comment by trlinden** [comment]
<img width="1598" alt="Screenshot 2024-08-16 at 10 35 32" src="https://github.com/user-attachments/assets/14052b8f-4fe4-4718-9cb1-25aa401ffd88">

When you add the vertical tab bar - this window pops up. When I did this originally, it had a list of all of the same tabs that are open in sidebery (so there was basically two mirrored lists of the tabs). I tried to fix this by going into the userChrome.css file and adding the lines:

#TabsToolbar-customization-target { visibility: collapse !important; }

#tabbrowser-tabs { visibility: collapse !important; }

This got rid of the list -- but I can't seem to get rid of the actual bar itself (so it still takes up screen real estate).

At the moment, I have mitigated this to some extent by turning off the vertical tab bar -- which (along with the two userChrome.css edits above), means that there is just a tiny gray bar on the top of the screen, which is less annoying.

**Comment by Alexcoder5** [comment]
Put it back to horizontal tabs if you are using Sidebery. Or you want to use native vertical tabs? If yes, I need to update userChrome to support it

**Comment by trlinden** [comment]
Aha! Sorry, I'm very dumb. I clicked the vertical tab bar option, instead of the "optimize for vertical tab bar" without actually clicking the experimental vertical tab bar support.....

Clicking "optimize for vertical tab bar" without selecting vertical tab bar itself makes everything work.

**Comment by Alexcoder5** [comment]
Glad you figured it out
